### ISSUE TITLE
AccountDaoの冗長な処理

### ISSUE THREAD

**Issue by f19ba073** [CIDResearch-8/swapping_positive#5]
findByNoメソッド内のif文は省いても同じ動作をします

該当コード
https://github.com/CIDResearch-8/swapping_positive/blob/6990b521362c68903bfc6ee2282e9eb684dfb900/src/main/java/com/swappingpositive/login/AccountDao.java#L19-L26

以下のように記述してもuser_id不一致時にnullを返すことができます。

`return (Account) map.get(username);`

**Comment by CIDResearch-8** [comment]
コミットID 2633605 にて修正いたしました。
該当コードの他、authAccountメソッドも修正しました。
